apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP   # Internal only, not exposed outside cluster
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
