apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: fastapi-app
spec:
  accessModes:
    - ReadWriteOnce  # Jeden pod naraz (OK dla Minikube)
  resources:
    requests:
      storage: 5Gi
