apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: "{{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}"
        imagePullPolicy: {{ .Values.fastapi.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.fastapi.service.port }}
        resources:
          {{- toYaml .Values.fastapi.resources | nindent 12 }}
