apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: fastapi
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: {{ .Values.fastapi.service.port }}