# FastAPI Configuration
fastapi:
  replicaCount: 3
  image:
    repository: fastapi-app
    tag: "v3"
    pullPolicy: Never
  service:
    type: LoadBalancer
    port: 8000
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ingress:
    enabled: true
    host: fastapi.local

# PostgreSQL Configuration
postgres:
  existingSecret: "postgres-secret"
  existingSecretPasswordKey: "POSTGRES_PASSWORD"

  image:
    repository: postgres
    tag: "16-alpine"
  storage:
    size: 1Gi
  database: "fastapi_db"
  user: "fastapi_user"
  password: "changeme"  # W produkcji: u≈ºyj --set lub secrets

# Namespace
namespace: fastapi-app
